plugins:
  - flowtype

extends:
  - airbnb
  - plugin:flowtype/recommended

env:
  browser: true
  node: true
  mocha: true
  es6: true

parserOptions:
  ecmaFeatures:
    modules: true
    jsx: true

settings:
  react:
    pragma: h
  import/resolver: webpack

rules:
  semi: ['error', 'never']
  'import/prefer-default-export': off
  'react/prop-types': off
  'react/no-unused-prop-types': off
