variables:
  COMPOSE_FILE: docker-compose.yml:docker/compose.build.yml

before_script:
  - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

stages:
  - build

cache:
  key: dependencies
  paths:
    - frontend/node_modules
    - frontend/flow-typed

build:
  stage: build
  tags: [docker]
  script:
    - docker-compose build rails
    - docker-compose run --rm -T -v $PWD/backend:/app rails bundle exec rails graphql:schema:dump
    - docker run --rm -v $PWD:/app -w /app/frontend node:10 bash -c "
        yarn install && yarn relay"
    - docker-compose build
    - docker-compose push
