version: '3.2'

networks:
  public_web:
    external: true

services:
  node:
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:$BASE_HOST"
      - "traefik.port=4000"
      - "traefik.frontend.entryPoints=https,http"
      - "traefik.docker.network=public_web"
    restart: unless-stopped
    networks:
      - public_web

  minio:
    restart: unless-stopped
    networks:
      - public_web
      - default
    labels:
      - traefik.docker.network=public_web
    volumes:
      - /data

  postgres:
    volumes:
      - /var/lib/postgresql

  rails:
    restart: unless-stopped
    networks:
      - public_web
      - default
    labels:
      - traefik.docker.network=public_web

  clockwork:
    restart: unless-stopped
