version: '3.6'

services:
  rails:
    build: ./backend
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${BASE_HOST-localhost};PathPrefix: /graphql"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=https,http"

  clockwork:
    image: rails
    env_file: .env
    command: bundle exec clockwork config/clock.rb

  postgres:
    image: postgres:10

  minio:
    image: minio/minio
    command: server /data
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.uploaddir.frontend.rule=Host:${BASE_HOST-localhost};PathPrefixStrip:/uploads"
      - "traefik.port=9000"
      - "traefik.frontend.entryPoints=https,http"
