version: '3.2'

services:
  rails:
    volumes: ['./backend:/app']
    tmpfs: /app/tmp
    ports: ['3000:3000']
    env_file: .env
    command: bash -c 'bundle install && rails s'
    environment:
      RAILS_ENV: development

  traefik:
    image: traefik
    ports: ['8080:8080', '80:80']
    command: --debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

  minio:
    ports: ['9000:9000']
    env_file: .env
    labels:
      - "traefik.admin.frontend.rule=PathPrefix:/minio"
