version: '3.2'

services:
  rails:
    volumes: ['./backend:/app']
    ports: ['3000:3000']
    command: bash -c 'bundle install && rails s'

  traefik:
    image: traefik
    ports: ['8080:8080', '80:80']
    command: --debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

  minio:
    ports: ['9000:9000']
    environment:
      MINIO_ACCESS_KEY: VFWURDFRT6EFJDSHVVQ2
      MINIO_SECRET_KEY: 9q3ySOQ9V7E+47Q5iNmUn50yzXOFlIGyPa25JUt3
    labels:
      - "traefik.admin.frontend.rule=PathPrefix:/minio"
