version: '3.6'

networks:
  public_web:
    external: true

services:
  node:
    image: $CI_REGISTRY_IMAGE/frontend
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:$BASE_HOST"
      - "traefik.port=4000"
      - "traefik.frontend.entryPoints=https,http"
      - "traefik.docker.network=public_web"
    restart: unless-stopped
    networks:
      - public_web
    build: /dev/null

  minio:
    restart: unless-stopped
    networks:
      - public_web
      - default
    labels:
      - traefik.docker.network=public_web
    volumes:
      - /data

  postgres:
    volumes:
      - /var/lib/postgresql

  rails:
    image: $CI_REGISTRY_IMAGE/backend
    restart: unless-stopped
    networks:
      - public_web
      - default
    labels:
      - traefik.docker.network=public_web
    build: /dev/null

  clockwork:
    image: $CI_REGISTRY_IMAGE/backend
    restart: unless-stopped
    build: /dev/null
