// flow-typed signature: c2641051d46ec6c16f442fc2e3db0fdf
// flow-typed version: <<STUB>>/node_v9/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node/installArchSpecificPackage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node/installArchSpecificPackage.js' {
  declare module.exports: $Exports<'node/installArchSpecificPackage'>;
}
